### PR TITLE
[Wiki] Add Banner

### PR DESCRIPTION
**Pull request by JSto91**
# Description of change

Based on @aleksei-korolev feedback i changed the main banner.

***NOTE:***  The banner "banner_wasp_core_concepts_architecture.png" is atm excluded since i think it's overloading the page.
(old version)[https://jsto91.github.io/iota-wiki/smart-contracts/guide/core_concepts/iscp-architecture]

If you have an idea where you would like to see it, share it 😄 
Else: The banner is already in the img/Banner folder so you could also add it to a page later yourself if you want :)

Add Banner to following pages:

- **Overview**
- Core Concepts/ **Smart Contracts**
- Core Concepts/ Core Contracts/ **Overview**
- ISC Chains and Nodes / **using Docker**

## How the change has been tested

https://gitpod.io/#https://github.com/JSto91/wasp/tree/add_banner

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have selected the `develop` branch as the target branch

### CODE REVIEW

**Review by jorgemmsilva — APPROVED** [review]

**Comment by jorgemmsilva** [comment]
those look great, thank you for the contribution!

**Comment by JSto91** [comment]
> those look great, thank you for the contribution!

Hey, thanks :) glad you guys like it

Out of curiosity, was there some failure in my branch? the tests failed and I didn't know what exactly the issue was 😅 
Didn't want to disturb you on a weekend - that's why i am asking now 😃

**Comment by jorgemmsilva** [comment]
Nothing wrong, we have 1 flaky test on develop that fails sometimes, and linting needs to be fixed because the linter was updated and we didn't update the code to follow the new rules yet. `develop` branch is kind of frozen right now as all efforts are on finishing the `stardust` update that will get merged into developed soon :)

**Comment by JSto91** [comment]
I see - thanks for the clarification :)

**Pull request merged**
