### PR TITLE
Docs - Develop - Dev Tools

### PR DESCRIPTION
**Pull request by lucas-tortora**
# Description of change

* A few small edits to the Dev Tools section
* Included full usage instructions.

## Type of change

- Documentation enhancement

## How the change has been tested

Wiki was built locally

## Change checklist

- [x] I have followed the [contribution guidelines](https://wiki.iota.org/smart-contracts/contribute) for this project
- [x] I have selected the `develop` branch as the target branch
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by lucas-tortora** [comment]
@dessaya , could you, or someone you see fit please review this?

**Comment by lucas-tortora** [comment]
@aleksei-korolev , could you please review this?

**Comment by aleksei-korolev** [comment]
There is a lot of code changes, do you target the right branch?

**Comment by lucas-tortora** [comment]
> There is a lot of code changes, do you target the right branch?

they come from a merge from [origin/develop](https://github.com/iotaledger/wasp/pull/1246/commits/655a53fb8b1d15ce284d58317e2e616962f2e445) to resolve a conflict.

**Comment by jorgemmsilva** [comment]
There are a bunch of conflicts in this PR, please resolve so it can be merged

**Pull request closed without merging**
