### PR TITLE
docs: fix typos in accounts.md

### PR DESCRIPTION
**Pull request by milgner**
And unify spelling of "authorize" to use american english throughout.

Just some drive-by corrections :wink:

### CODE REVIEW

**Review by jorgemmsilva — APPROVED** [review]

**Comment by BugFreeSoftware** [comment]
Could you please make this a pull-request for the develop branch instead of master?

**Comment by milgner** [comment]
Thank you @jorgemmsilva  :+1: - I created the PR from the "Edit Page on Github" link and assumed that the default branch was the correct one.

**Comment by lunfardo314** [comment]
@milgner could you delete the PR  and then issue the PR again to the `develop` branch?

**Comment by milgner** [comment]
Sure thing, will do :+1:  - I had assumed that changing the target branch in the MR had been enough.

**Pull request closed without merging**
