### PR TITLE
BugFix for "ApplyBlock: b state index #x can't be applied to the empty state"

### PR DESCRIPTION
**Pull request by Juliusan**
A fix for a bug, which didn't allow to apply any blocks to the state, which is loaded from the DB and is not an origin state. A test, checking this exact situation, is also included. All the regular tests pass. Heavy tests not run.

### CODE REVIEW

**Review by jorgemmsilva — APPROVED** [review]
LGTM, but maybe it can be simplified.

Can't we have a single function, instead of applyBock and applyAnyBlock?

It's just checking if the index and timestamp match not enough? Why do we need the "empty" flag?

**Comment by Juliusan** [comment]
`empty` flag is needed for applying origin block to origin state. If `vs` is an origin state, it doesn't have a block index (and, possibly a timestamp), so `vs.BlockIndex()+1 != b.BlockIndex()` (more precisely `vs.BlockIndex()`) would throw an error.

Another approach would be to somehow catch this situation in `ApplyBlock` method. However, I think, my way is better: in this case, there is an exception for origin block only and no need to check this indirectly.

**Comment by jorgemmsilva** [comment]
Any reason for the "origin state" to not come with the "origin block" already? :smile:

**Comment by Juliusan** [comment]
Haven't dived that deep :-D

**Pull request merged**
