### PR TITLE
fix: Conduct proper aud, iss, and sub in jwt

### PR DESCRIPTION
**Pull request by howjmay**
The issuer has been changed to the public key of the nodeID

### CODE REVIEW

**Review by lmoe — APPROVED** [review]
Looks good. 
I hope we have at some point a proper auth provider than can span over multiple nodes.

**Comment by howjmay** [comment]
> Looks good. I hope we have at some point a proper auth provider than can span over multiple nodes.

@lmoe I don't understand this. Would you mind providing more information then I can add them as TODO in codebase

**Comment by lmoe** [comment]
@howjmay Don't worry about it for now, it should when rather be a proper task.

The problem is that each node has a different private key and all JWT tokens are signed with a private key. 

When you put multiple Wasp nodes behind a load balancer, the JWT token validation will fail on all nodes except the one which has signed it.

One option to solve this, is a separate auth service node that signs/validates tokens and handles the logins. 
All Wasp nodes would connect to this service and ask for token validation when a request comes in.

So we would basically need to move all auth related parts to a separate node, write an API around it and deploy it with the Wasp nodes - or even better, use a full fledged oidc service that most likely exists already anyway. 

But I would not spend time on it right now. :)

**Comment by howjmay** [comment]
> 

wow I won't either Then I am going to merge this one

**Pull request merged**
