### PR TITLE
Update devnet to Hornet

### PR DESCRIPTION
**Pull request by lmoe**
# Description of change
Replaces the GoShimmer node with a Hornet setup. 
DockerImage was changed from `buster` to `bullseye` as librocksdb doesn't build on `buster`.

This includes the new hornet-nest image, keeping the folder clean. 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

### CODE REVIEW

**Review by jorgemmsilva — COMMENTED** [review]
not a big fan of copying these files from the Hornet repo. I would rather have a link to the correct files on the original source

**Comment by lmoe** [comment]
Yeah me neither, but they compile Hornet by source. I want a fixed hornet docker version for now to keep things stable.

**Review by jorgemmsilva — APPROVED** [review]
I guess lets merge this to have the docs in a "usable state" for now, even if we should move to a "low maintenance", easier to setup version in the future.

**Comment by howjmay** [comment]
I think rebase to the latest commit on develop branch can solve the required branch protection

**Comment by jorgemmsilva** [comment]
@HowJMay yeah that is okay, just re-running the ci jobs should fix this.
We're waiting on another docker image from hornet that will make this setup much much simpler.

**Comment by lmoe** [comment]
The bloated setup was now replaced with the new hornet-nest image. I've tested it with a locally built hornet-nest image and it works fine. Once the next Hornet release comes up, we can merge. @jorgemmsilva

**Pull request merged**
