### PR TITLE
Replace trie cache

### PR DESCRIPTION
**Pull request by luke-thorne**
# Description of change

Change trie cache from golang-lru to fastcache.
See #2485 for benchmarking details with some alternatives.

## Links to any relevant issues

#2485 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

- Ran benchmarks against several caches, the interface used with the cache does not change. 
- ran `make test`

### CODE REVIEW

**Review by dessaya — APPROVED** [review]
Awesome!

We are using golang-lru in 3 other places, should we change those as well? So that we use the same thing everywhere.

**Comment by luke-thorne** [comment]
@dessaya 
I'm not sure how to convert `*state` to `[]byte` for `state.state`.

Can you help me with this function? [packages/state/store.go:50
](https://github.com/iotaledger/wasp/blob/76327bc136557710cbf8d8b3f22935d9864d1770/packages/state/store.go#L50)
```go
func (s *store) stateByTrieRoot(root trie.Hash) (*state, error) {
	if r := s.stateCache.GetBig(nil, root.Bytes()); r != nil {
		return &state{}, nil
	}
	r, err := newState(s.db, root)
	if err != nil {
		return nil, err
	}
	s.stateCache.SetBig(root.Bytes(), r)
	return r, nil
}
```

**Comment by dessaya** [comment]
hmmm... it seems that in this case fastcache is not very useful, because it only allows to store `[]byte` values. We want to keep a cache of `*State` instances, not `[]byte`.

**Comment by luke-thorne** [comment]
Thought about forking fastcache to allow setting types with generics but they base their whole cache on a ring buffer with encoded (k, v) pairs so the length of bytes in both the key and value is essential. Do we try fastcache in the other 2 places and leave lru here or just leave it all as lru?

I could fork clockpro and make it a typed cache like lru is but it is slower according to my benchmarks.
@dessaya

**Comment by dessaya** [comment]
Let's use fastcache wherever it makes sense and keep golang-lru elsewhere. Thanks!

**Pull request merged**
